# This is a basic workflow to help you get started with Actions

name: Compile Zine

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build Pages via Tectonic
      uses: LiHRaM/tectonic-nix@master
      with:
        # Path to master file.
        file: 'pages.tex'
    - name: Build Zine via Tectonic
      uses: LiHRaM/tectonic-nix@master
      with:
        # Path to master file.
        file: 'zine.tex'
    - name: Save PDFs
      uses: actions/upload-artifact@v2-preview
      with:
        name: 'Output'
        path: '*.pdf'
